version: '3'

services:
  frontend:
    build:
      context: ./chat
      dockerfile: Dockerfile
      args:
        - VITE_APP_HOST=https://filin-hub.online/api
        - VITE_APP_HOST_WEB_SOCKET=ws://filin-hub.online/api
        - VITE_APP_PROTOCOL=ws
    ports:
      - '8080:80'
    depends_on:
      - backend

  backend:
    build:
      context: ./chat_api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - database

  database:
    image: postgres:15
    env_file: .env
    restart: always
    volumes:
      - /var/postgress_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
