version: '3'

services:
  frontend:
    build:
      context: ./chat
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - backend

bot:
  build:
    context: ./question_bot
    dockerfile: Dockerfile
  ports:
    - '4000:4000'
  depends_on:
    - backend

  backend:
    build:
      context: ./chat_api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - database

  database:
    image: postgres:15
    env_file: .env
    restart: always
    volumes:
      - /var/postgress_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
